version: '3.9'

services:
  frontend:
	  build:
  	  context: ./frontend
  	  dockerfile: Dockerfile
	  ports:
  	  - "5173:5173"
	  volumes:
  	  - ./frontend:/app
  	  - /app/node_modules
	  environment:
  	  - NODE_ENV=development
	  command: npm run dev

  node-backend:
	  build:
  	  context: ./node-backend
  	  dockerfile: Dockerfile
	  ports:
  	  - "3000:3000"
	  volumes:
  	  - ./node-backend:/app
  	  - /app/node_modules
	  environment:
  	  - NODE_ENV=development
	  command: npm start

  tomcat:
	  image: tomcat:9.0
	  ports:
  	  - "8080:8080"
	  volumes:
  	  - ./tomcat/webapps:/usr/local/tomcat/webapps
	  environment:
  	  - JAVA_OPTS=-Xms512m -Xmx1024m
